const projects = [
  {
    id: 'wardrobe-wise',
    index: '01',
    title: '衣橱决策助手',
    titleEn: 'Wardrobe Wise',
    type: 'AI 消费决策产品',
    typeEn: 'AI-assisted consumer decisions',
    date: '2026',
    cover: '/project-wardrobe.png',
    link: '/projects/wardrobe-wise',
    linkEn: '/en/projects/wardrobe-wise',
    liveLink: 'https://wardrobe-wise-fit.zainanfang999.chatgpt.site',
    summary: '购买前，先问问自己的衣橱。让推荐建立在用户已经拥有什么之上。',
    summaryEn: 'Before buying something new, start with what is already in the wardrobe. Recommendations become more useful when they understand the user’s existing clothes.',
    outcome: '记录衣橱 → 分析结构 → 评估购买 → 回看消费',
    outcomeEn: 'Capture wardrobe → Map gaps → Evaluate purchases → Learn from outcomes',
    role: '产品定义 / 信息架构 / AI 交互 / 原型验证',
    roleEn: 'Product definition / Information architecture / AI interaction / Prototype validation',
    problem: '常见购物建议只理解商品，却不了解用户已有的衣物、穿着场景与重复购买。',
    problemEn: 'Most shopping assistants understand products, but not the clothes a person already owns, the situations they dress for, or the patterns behind repeat purchases.',
    approach: ['建立个人衣橱档案，把用户现状变成购买判断的基础。', '将模糊偏好拆成颜色、版型、场景、搭配空间与重复度。', '把购买后的反馈重新写回衣橱，形成长期决策闭环。'],
    approachEn: [
      'Build a personal wardrobe profile so every recommendation starts from the user’s real context.',
      'Translate vague preferences into colour, silhouette, occasion, styling potential and duplication signals.',
      'Feed post-purchase reflections back into the wardrobe to create a long-term decision loop.',
    ],
    result: '从一次性的商品问答，转向可积累、可回看的个人消费决策系统。',
    resultEn: 'The concept moves beyond one-off product Q&A into a personal decision system that becomes more useful over time.',
    tags: ['多模态 AI', '消费决策', '用户画像', '闭环设计'],
    tagsEn: ['Multimodal AI', 'Purchase decisions', 'User modelling', 'Closed-loop design'],
  },
  {
    id: 'geofield',
    index: '02',
    title: 'GeoField Analyzer',
    titleEn: 'Spatial Data Workflow',
    type: '空间数据工作流',
    typeEn: 'Spatial data workflow',
    date: '2026',
    cover: '/project-geofield.png',
    link: '/projects/geofield',
    linkEn: '/en/projects/geofield',
    liveLink: '/demos/geofield.html',
    summary: '让分散的 KMZ 与现场数据，快速变成可以直接分析的空间证据。',
    summaryEn: 'Turn scattered KMZ files and field records into spatial evidence that is ready for analysis.',
    outcome: '约 10 小时 → 5 分钟',
    outcomeEn: 'Approx. 10 hours → 5 minutes',
    role: '需求拆解 / 工作流重构 / 前端实现 / 任务测试',
    roleEn: 'Requirements analysis / Workflow redesign / Front-end implementation / Task testing',
    problem: '多被试现场数据需要反复解压、匹配、整理和制图，耗时且容易错位。',
    problemEn: 'Field data from multiple participants required repeated extraction, matching, organisation and mapping—a slow process with many opportunities for misalignment.',
    approach: ['把导入、解析、照片匹配、可视化与导出连接成单一路径。', '将异常点与缺失信息显性化，避免自动化悄悄制造错误。', '用真实 KMZ 数据回放流程，持续压缩操作成本。'],
    approachEn: [
      'Connect import, parsing, photo matching, visualisation and export in one continuous workflow.',
      'Surface anomalies and missing information so automation never hides data-quality issues.',
      'Replay the workflow with real KMZ datasets and iteratively remove unnecessary operations.',
    ],
    result: '把重复的数据整理工作转化为可检查、可复用的现场分析工具。',
    resultEn: 'A repetitive data-cleaning task became a reusable and inspectable field-analysis tool.',
    tags: ['GIS', '工作流自动化', '数据可视化', '效率提升'],
    tagsEn: ['GIS', 'Workflow automation', 'Data visualisation', 'Operational efficiency'],
  },
  {
    id: 'scene-survey',
    index: '03',
    title: '场景实验问卷工具',
    titleEn: 'Research Survey Builder',
    type: '科研流程自动化',
    typeEn: 'Research workflow automation',
    date: '2026',
    cover: '/project-survey.png',
    link: '/projects/scene-survey',
    linkEn: '/en/projects/scene-survey',
    liveLink: '/demos/survey.html',
    summary: '连接研究者配置端与被试填写端，让场景问卷从手工排版变成自动生成。',
    summaryEn: 'Connect the researcher setup flow with the participant experience, replacing manual survey formatting with automated generation.',
    outcome: '单份配置 30 分钟 → 1 分钟',
    outcomeEn: 'Setup time per survey: 30 minutes → 1 minute',
    role: '双角色流程 / 配置逻辑 / 数据质量 / 原型实现',
    roleEn: 'Dual-role workflow / Configuration logic / Data quality / Prototype implementation',
    problem: '现场照片、点位与量表需要逐份手工整理，被试越多，重复劳动和错误越多。',
    problemEn: 'Field photos, locations and rating scales had to be assembled manually for every survey. As participant numbers grew, so did repetitive work and errors.',
    approach: ['区分研究者配置与被试填写两类任务，分别降低认知负担。', '按拍摄时间自动排序场景，并把照片、点位和题项绑定。', '加入进度、缺失提醒与结构化导出，保证后续分析质量。'],
    approachEn: [
      'Separate researcher configuration from participant completion to reduce cognitive load for both roles.',
      'Sort scenes by capture time and bind each photograph to its location and question set.',
      'Add progress tracking, missing-data prompts and structured export to protect downstream analysis quality.',
    ],
    result: '把问卷制作从一次性文档劳动，转化为可复用的研究流程。',
    resultEn: 'Survey production changed from one-off document work into a reusable research workflow.',
    tags: ['用户研究', '双角色产品', '自动化', '数据质量'],
    tagsEn: ['User research', 'Dual-role product', 'Automation', 'Data quality'],
  },
];

export default projects;
