const projects = [
  {
    id: 'wardrobe-wise',
    index: '01',
    title: '衣橱决策助手',
    titleEn: 'Wardrobe Wise',
    type: 'AI 消费决策产品',
    typeEn: 'AI-assisted consumer decisions',
    date: '2026',
    cover: '/project-wardrobe.png',
    link: '/projects/wardrobe-wise',
    linkEn: '/en/projects/wardrobe-wise',
    liveLink: 'https://wardrobe-wise-fit.zainanfang999.chatgpt.site',
    summary: '购买前，先问问自己的衣橱。让推荐建立在用户已经拥有什么之上。',
    summaryEn: 'Before buying something new, start with what is already in the wardrobe. Recommendations become more useful when they understand the user’s existing clothes.',
    outcome: '记录衣橱 → 分析结构 → 评估购买 → 回看消费',
    outcomeEn: 'Capture wardrobe → Map gaps → Evaluate purchases → Learn from outcomes',
    role: '产品定义 / 信息架构 / AI 交互 / 原型验证',
    roleEn: 'Product definition / Information architecture / AI interaction / Prototype validation',
    problem: '常见购物建议只理解商品，却不了解用户已有的衣物、穿着场景与重复购买。',
    problemEn: 'Most shopping assistants understand products, but not the clothes a person already owns, the situations they dress for, or the patterns behind repeat purchases.',
    approach: ['建立个人衣橱档案，把用户现状变成购买判断的基础。', '将模糊偏好拆成颜色、版型、场景、搭配空间与重复度。', '把购买后的反馈重新写回衣橱，形成长期决策闭环。'],
    approachEn: [
      'Build a personal wardrobe profile so every recommendation starts from the user’s real context.',
      'Translate vague preferences into colour, silhouette, occasion, styling potential and duplication signals.',
      'Feed post-purchase reflections back into the wardrobe to create a long-term decision loop.',
    ],
    result: '从一次性的商品问答，转向可积累、可回看的个人消费决策系统。',
    resultEn: 'The concept moves beyond one-off product Q&A into a personal decision system that becomes more useful over time.',
    tags: ['多模态 AI', '消费决策', '用户画像', '闭环设计'],
    tagsEn: ['Multimodal AI', 'Purchase decisions', 'User modelling', 'Closed-loop design'],
  },
  {
    id: 'geofield',
    index: '02',
    title: 'GeoField Analyzer',
    titleEn: 'Spatial Data Workflow',
    type: '空间数据工作流',
    typeEn: 'Spatial data workflow',
    date: '2026',
    cover: '/project-geofield.png',
    link: '/projects/geofield',
    linkEn: '/en/projects/geofield',
    liveLink: '/demos/geofield.html',
    summary: '让分散的 KMZ 与现场数据，快速变成可以直接分析的空间证据。',
    summaryEn: 'Turn scattered KMZ files and field records into spatial evidence that is ready for analysis.',
    outcome: '约 10 小时 → 5 分钟',
    outcomeEn: 'Approx. 10 hours → 5 minutes',
    role: '需求拆解 / 工作流重构 / 前端实现 / 任务测试',
    roleEn: 'Requirements analysis / Workflow redesign / Front-end implementation / Task testing',
    problem: '多被试现场数据需要反复解压、匹配、整理和制图，耗时且容易错位。',
    problemEn: 'Field data from multiple participants required repeated extraction, matching, organisation and mapping—a slow process with many opportunities for misalignment.',
    approach: ['把导入、解析、照片匹配、可视化与导出连接成单一路径。', '将异常点与缺失信息显性化，避免自动化悄悄制造错误。', '用真实 KMZ 数据回放流程，持续压缩操作成本。'],
    approachEn: [
      'Connect import, parsing, photo matching, visualisation and export in one continuous workflow.',
      'Surface anomalies and missing information so automation never hides data-quality issues.',
      'Replay the workflow with real KMZ datasets and iteratively remove unnecessary operations.',
    ],
    result: '把重复的数据整理工作转化为可检查、可复用的现场分析工具。',
    resultEn: 'A repetitive data-cleaning task became a reusable and inspectable field-analysis tool.',
    tags: ['GIS', '工作流自动化', '数据可视化', '效率提升'],
    tagsEn: ['GIS', 'Workflow automation', 'Data visualisation', 'Operational efficiency'],
  },
  {
    id: 'scene-survey',
    index: '03',
    title: '场景实验问卷工具',
    titleEn: 'Research Survey Builder',
    type: '科研流程自动化',
    typeEn: 'Research workflow automation',
    date: '2026',
    cover: '/project-survey.png',
    link: '/projects/scene-survey',
    linkEn: '/en/projects/scene-survey',
    liveLink: '/demos/survey.html',
    summary: '连接研究者配置端与被试填写端，让场景问卷从手工排版变成自动生成。',
    summaryEn: 'Connect the researcher setup flow with the participant experience, replacing manual survey formatting with automated generation.',
    outcome: '单份配置 30 分钟 → 1 分钟',
    outcomeEn: 'Setup time per survey: 30 minutes → 1 minute',
    role: '双角色流程 / 配置逻辑 / 数据质量 / 原型实现',
    roleEn: 'Dual-role workflow / Configuration logic / Data quality / Prototype implementation',
    problem: '现场照片、点位与量表需要逐份手工整理，被试越多，重复劳动和错误越多。',
    problemEn: 'Field photos, locations and rating scales had to be assembled manually for every survey. As participant numbers grew, so did repetitive work and errors.',
    approach: ['区分研究者配置与被试填写两类任务，分别降低认知负担。', '按拍摄时间自动排序场景，并把照片、点位和题项绑定。', '加入进度、缺失提醒与结构化导出，保证后续分析质量。'],
    approachEn: [
      'Separate researcher configuration from participant completion to reduce cognitive load for both roles.',
      'Sort scenes by capture time and bind each photograph to its location and question set.',
      'Add progress tracking, missing-data prompts and structured export to protect downstream analysis quality.',
    ],
    result: '把问卷制作从一次性文档劳动，转化为可复用的研究流程。',
    resultEn: 'Survey production changed from one-off document work into a reusable research workflow.',
    tags: ['用户研究', '双角色产品', '自动化', '数据质量'],
    tagsEn: ['User research', 'Dual-role product', 'Automation', 'Data quality'],
  },
  {
    id: 'cubist-fountain',
    index: '04',
    title: 'Cubist Fountain',
    titleEn: 'Cubist Fountain',
    type: '多模态 AI × 参数化设计',
    typeEn: 'Multimodal AI × Parametric Design',
    date: '2026',
    cover: '/projects/cubist-fountain/cover-poster.webp',
    coverMotion: '/projects/cubist-fountain/cover-assembly.webp',
    coverFit: 'cover',
    link: '/projects/cubist-fountain',
    linkEn: '/en/projects/cubist-fountain',
    liveLink: 'https://github.com/lugaorunf-max/cubist-fountain',
    ctaLabel: '查看项目仓库',
    ctaLabelEn: 'VIEW REPOSITORY',
    summary: '从课程设计出发，将抽象视觉意图拆解为可执行的几何规则，并贯通参数化建模、AI 渲染与实体原型制作。',
    summaryEn: 'A course-design project that translates abstract visual intent into executable geometry, parametric models, AI renders and physical prototypes.',
    outcome: '视觉意图 → 几何规则 → GhPython → 实体原型',
    outcomeEn: 'Visual intent → Geometric rules → GhPython → Physical prototype',
    role: '全流程参与：课设定义 / 视觉推理 / 规则提取 / Prompt 迭代 / GhPython 建模 / 原型制作 / 仓库沉淀',
    roleEn: 'Full-cycle contributor: course brief / visual reasoning / rule extraction / prompt iteration / GhPython modelling / prototyping / repository documentation',
    problem: '多模态模型能够描述图像，却很难稳定地产出可运行、可调参且忠于设计意图的参数化几何。',
    problemEn: 'Multimodal models can describe an image, but they do not reliably produce executable, editable parametric geometry that preserves the original design intent.',
    approach: [
      '把“看图直接生成代码”拆成视觉推理、设计语法与代码生成三层转译，让每一层都可以被人工检查。',
      '用 Role、Task、Constraints、Input、Output 与 Verification 组织提示词，把模糊审美判断改写成旋转、偏移、阵列、相交与挤出等几何动作。',
      '禁止不可控随机性，为固定值和可调参数分别设定范围，使生成结果可复现、可继续设计。',
      '用参数化模型、装配动画和实体原型反向验证规则，将一次课程作业沉淀为可复用工作流。',
    ],
    approachEn: [
      'Split image-to-code generation into three inspectable layers: visual reasoning, design grammar and code generation.',
      'Structure prompts through Role, Task, Constraints, Input, Output and Verification, replacing vague aesthetic language with operations such as rotate, offset, array, intersect and extrude.',
      'Remove uncontrolled randomness and define ranges for fixed and editable parameters so results remain reproducible and open to further design.',
      'Validate the rules through parametric models, assembly motion and physical prototypes, turning a course assignment into a reusable workflow.',
    ],
    result: '形成一套从抽象图像到可编辑参数化模型的多模态 AI 方法，并完成从设计分析到实体制作的完整闭环。',
    resultEn: 'A reusable multimodal AI method now connects abstract visual references to editable parametric models and a complete physical-delivery loop.',
    tags: ['多模态 AI', 'Grasshopper', 'GhPython', '形状文法', '实体原型'],
    tagsEn: ['Multimodal AI', 'Grasshopper', 'GhPython', 'Shape grammar', 'Physical prototyping'],
    media: [
      {
        src: '/projects/cubist-fountain/workflow-assembly.webp',
        animated: true,
        title: '构件装配逻辑',
        titleEn: 'Assembly logic',
        description: '将生成结果拆解为可识别的层级与构件，检查几何规则如何汇合成完整空间。',
        descriptionEn: 'The generated model is decomposed into legible layers and parts, revealing how separate geometric rules converge into one spatial system.',
      },
      {
        src: '/projects/cubist-fountain/workflow-rotation.webp',
        animated: true,
        title: '参数化模型验证',
        titleEn: 'Parametric model validation',
        description: '通过连续视角检查体块关系、穿插逻辑与模型的整体可读性。',
        descriptionEn: 'A continuous rotation checks massing, intersections and the overall legibility of the generated model.',
      },
      {
        src: '/projects/cubist-fountain/prototype.webp',
        animated: false,
        title: '实体原型交付',
        titleEn: 'Physical prototype',
        description: '用实体模型验证尺度、构造与负形关系，让数字生成结果最终回到可触摸的设计对象。',
        descriptionEn: 'Physical models test scale, construction and negative space, returning the digital workflow to a tangible design object.',
      },
    ],
  },
];

export default projects;
